version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  jupyter:
    build:
      context: ./analytics
      dockerfile: Dockerfile 
    ports:
      - "8888:8888"
    depends_on:
      - db
